### ISSUE TITLE
ijj

### ISSUE THREAD

**Issue by ghost** [ColinWaddell/WPSuperControl#1]

**Comment by jigar787** [comment]
[yjs.txt](https://github.com/ColinWaddell/WPSuperControl/files/3060974/yjs.txt)
[yw.txt](https://github.com/ColinWaddell/WPSuperControl/files/3060975/yw.txt)
[yfun.txt](https://github.com/ColinWaddell/WPSuperControl/files/3060976/yfun.txt)
